Views gets list of lyrics rodney
kali-physi-hacker/lyrics pull request #8
Opened 2021-03-22 16:14 UTC by RJ-0605

this PR is for the changes made in the api , changes to the view and the url  in the api app

2021-03-22 18:10 UTC, kali-physi-hacker commented
You should link this PR to its issue.

2021-03-22 18:24 UTC, kali-physi-hacker requested changes

2021-03-22 18:24 UTC, kali-physi-hacker commented on api/views.py
> +def Get_LyricsList(request): # new
this is not a good naming convention. functions should always be in small letters. You could just use `lyrics_list` that's fine

2021-03-22 18:24 UTC, kali-physi-hacker commented on api/views.py
> +    except Lyric.DoesNotExist:
There was no need for this (I mean the `try` and `except`. Basically, when you do `Lyric.objects.all()`, a queryset is returned, This means when there are no lyrics no exception is raised but rather an empty set (or a set with no elements). So there's no need to wrap in a `try` and `except` block.

2021-03-22 18:24 UTC, kali-physi-hacker commented on api/views.py
> +        return HttpResponse(status=404)
And I don't know why you're returning an `HttpResponse` here???, even if the above logic, would work, you should not be returning `HttpResponse` but rather `Response` (a djangorestframework modified version for api responses).

2021-03-22 18:24 UTC, kali-physi-hacker commented on api/views.py
> +            return Response (serializer.data)
The was all you needed. not the above code. Also, to remember that **explicit is better than implicit**. so the last line should have been `return Response(datat=serializer.data, status=status.HTTP_200_OK).

2021-03-22 18:24 UTC, kali-physi-hacker commented on api/views.py
> +
you shouldn't be leaving unneeded comments in PRs

2021-03-22 18:24 UTC, kali-physi-hacker commented
Please make those changes asap. And remember to link the issue to the PR. We are wasting a lot of time over these.

2021-03-24 09:02 UTC, kali-physi-hacker requested changes

2021-03-24 09:02 UTC, kali-physi-hacker commented on api/urls.py
> +    path("/getlyricslist/", lyrics_list, name="lyrics_list")
`/lyrics/` should be used instead.

2021-03-24 09:02 UTC, kali-physi-hacker commented on api/views.py
> +
too much spacing.

2021-03-24 09:02 UTC, kali-physi-hacker commented on api/views.py
> +
running black will clear all these whitespace.

2021-03-24 20:29 UTC, kali-physi-hacker requested changes

2021-03-24 20:29 UTC, kali-physi-hacker commented on api/views.py
> +from django.http import HttpResponse, JsonResponse
this line is no longer needed, I guess?

2021-03-24 20:29 UTC, kali-physi-hacker commented on api/views.py
Also, you can take that off, we don't need that either?

2021-03-24 20:35 UTC, RJ-0605 commented on api/views.py
> +        # get lyrics from model
i think the current code is not spaced

2021-03-25 05:57 UTC, kali-physi-hacker approved these changes

2021-03-25 05:57 UTC, merged